### ISSUE TITLE
Change text of save button when viewing projects of other users

### ISSUE THREAD

**Issue by chartinger** [badlogic/paperbots#101]
To make it more clear that you can (and i guess the intention is to even encourage it) to expand on the work of someone else i suggest changing the text of the save button when viewing other projects to e.g.

- Make a copy
- Create a Remix (even if remix info is not yet saved as in #99)

**Comment by badlogic** [comment]
No, I think it makes more sense to keep it as is, the less buttons the better. You are being told what happens when you save someone elses project. However, I need to store the "remix" info somewhere and display the original source link.
