### ISSUE TITLE
Moaaaar robot functions

### ISSUE THREAD

**Issue by badlogic** [badlogic/paperbots#32]
- [x] getDirection()
- [x] getX()/getY()
- [x] get/setSpeed()
- [x] get/setTurningSpeed()
- [x] buildWall()
- [x] destroyWall()
- [x] distanceToWall()
- [x] backward()
- [ ] turnNorth()/...
- [ ] shoot()
- [ ] forward(x)
- [ ] backward(x)
- [ ] turnLeft(x)
- [ ] turnRight(x)

**Comment by NathanSweet** [comment]
distanceToWall()
forward(x)
backward()
backward(x)
turnLeft(x)
turnRight(x)
