### ISSUE TITLE
Speed functions inconsistent

### ISSUE THREAD

**Issue by chartinger** [badlogic/paperbots#54]
As from the docs

> setSpeed(speed: number)
> Sets the movement speed of the robot which is measured in number of cells per second

and

> setTurningSpeed(seconds: number)
> Set how long it takes the robot to turn by 90 degrees in seconds. 

both use the term speed, but: in the first case a higher number is faster (as expected), but the opposite is true in the second case.

**Comment by badlogic** [comment]
Good catch, @nathansweet also found this. I'll have fun fixing everybodies code :D
